function plotPwelch(C3LeftPwelch,C3RightPwelch,C4LeftPwelch,C4RightPwelch,freq)
    figure
    subplot(2,2,1)
    plot(freq,mean(C3LeftPwelch,2),'b')
    %sgtitle('C3_left')
    ylabel('Power')
    subplot(2,2,2)
    plot(freq,mean(C4LeftPwelch,2),'b')
    %sgtitle('C4_left')
    legend('left')
    subplot(2,2,3)
    plot(freq,mean(C3RightPwelch,2),'r')
    %sgtitle('C3_right')
    subplot(2,2,4)
    plot(freq,mean(C4RightPwelch,2),'r')
    %sgtitle('C4_right')
    xlabel('Frequency[Hz]')
    legend('right')
    
end
